services:
    fuseki:
        image: stain/jena-fuseki
        container_name: fuseki
        user: 0:0 # only giving access to mounted volumes as root 🙄
        ports:
            - 3030:3030
        environment:
            - ADMIN_PASSWORD=admin
        volumes:
            - ./data/fuseki:/fuseki
